vim.api.nvim_set_hl(0, "@keyword.function", { fg = "#c300ff", bold = true, italic = true })
vim.api.nvim_set_hl(0, "PreProc", { fg = "#c300ff", bold = true, italic = true })
vim.api.nvim_set_hl(0, "@keyword", { fg = "#c300ff", bold = true, italic = true })
vim.api.nvim_set_hl(0, "@operator", { fg = "#d4136d", bold = true })
vim.api.nvim_set_hl(0, "Function", { fg = "#1500ff", bold = true })
vim.api.nvim_set_hl(0, "@function", { fg = "#1500ff", bold = true })
vim.api.nvim_set_hl(0, "Special", { fg = "#1500ff" })
vim.api.nvim_set_hl(0, "@Constructor", { fg = "#117bac" })
vim.api.nvim_set_hl(0, "@String", { fg = "#76aa68" })
vim.api.nvim_set_hl(0, "@variable", { fg = "#a84aff" })
vim.api.nvim_set_hl(0, "@parameter", { fg = "#a84aff" })
vim.api.nvim_set_hl(0, "@field", { fg = "#5560ff" })
vim.api.nvim_set_hl(0, "@property", { fg = "#5560ff" })
vim.api.nvim_set_hl(0, "@variable.builtin", { fg = "#117bac" })
vim.api.nvim_set_hl(0, "Constant", { fg = "#117bac" })
vim.api.nvim_set_hl(0, "@Type", { fg = "#00b7ff" })
